// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANVUHymB7jIrA7RyP6xcN7l6e9x-2TPnA',
    appId: '1:1070746257308:web:eb28d8f6d663fee192aa59',
    messagingSenderId: '1070746257308',
    projectId: 'full-store-app',
    authDomain: 'full-store-app.firebaseapp.com',
    storageBucket: 'full-store-app.appspot.com',
    measurementId: 'G-YWD4F8QDB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ2NJx84nX9YqE7bb6mSw76uEOx7mGCnM',
    appId: '1:1070746257308:android:4493c11b992a595592aa59',
    messagingSenderId: '1070746257308',
    projectId: 'full-store-app',
    storageBucket: 'full-store-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-JxJqG0qavTFbDr4ZG5ac0BSYcyMMBYY',
    appId: '1:1070746257308:ios:5f36489a844afc4192aa59',
    messagingSenderId: '1070746257308',
    projectId: 'full-store-app',
    storageBucket: 'full-store-app.appspot.com',
    iosBundleId: 'com.example.fullStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-JxJqG0qavTFbDr4ZG5ac0BSYcyMMBYY',
    appId: '1:1070746257308:ios:0c7373b973e017ef92aa59',
    messagingSenderId: '1070746257308',
    projectId: 'full-store-app',
    storageBucket: 'full-store-app.appspot.com',
    iosBundleId: 'com.example.fullStoreApp.RunnerTests',
  );
}
